- name: Create Jenkins Jobs
  hosts: localhost
  roles:
    - jenkins

  vars:
    folders:
      - { folder_name: "CI-Pipelines" }
      - { folder_name: "Infra-Jobs" }
      #- { folder_name: "Deployment-Jobs" }
    mjobs:
      - { job_name: "cart", repo_name: "https://github.com/BhanuSaiReddy/cart" , folder_name: "CI-Pipelines" }

    sjobs:
      - { job_name: "roboshop-terraform", repo_name: "https://github.com/BhanuSaiReddy/roboshop-terraform" , folder_name: "Infra-Jobs"}