- name: Create Jenkins Jobs
  hosts: localhost
  roles:
    - jenkins

  mjobs:
    - { job_name: "cart", repo_name: "https://github.com/BhanuSaiReddy/cart"}

    sjobs:
      - { job_name: "roboshop-terraform", repo_name: "https://github.com/BhanuSaiReddy/roboshop-terraform"}